apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: teammapper
  namespace: shturval-cd
spec:
  description: TeamMapper
  sourceRepos:
    - https://github.com/vutratenko/teammapper-helm.git
  destinations:
    - namespace: teammapper
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
